context("Features: Linear Model")

test_that("A cell mapping-enabled FeatureObject is required", {
  feat.object = createFeatureObject(init = iris[, -5], objective = "Sepal.Length")
  expect_error(calculateLinearModelFeatures(feat.object))
})

test_that("calculateLinearModelFeatures -- first use case", {
  feat.object = createFeatureObject(init = iris[, -5], objective = "Sepal.Length", blocks = 3)
  features = calculateLinearModelFeatures(feat.object)
  expect_equal(length(features), 14L)
  expect_is(features, class = "list")
  expect_equal(as.character(sapply(features, class)), c(rep("numeric", 12L), "integer", "numeric"))
  expect_true( testNumber(features$limo.avg.length, lower = 0) )
  expect_true( testNumber(features$limo.avg.length.scaled, lower = 0, upper = 1) )
  expect_true( testNumber(features$limo.length.mean, lower = 0) )
  expect_true( testNumber(features$limo.length.sd, lower = 0) )
  expect_true( testNumber(features$limo.cor, lower = -1, upper = 1) )
  expect_true( testNumber(features$limo.cor.scaled, lower = -1, upper = 1) )
  expect_true( testNumber(features$limo.ratio.mean) )
  expect_true( testNumber(features$limo.ratio.sd, lower = 0) )
  expect_true( testNumber(features$limo.sd.max_min_ratio, lower = 1) )
  expect_true( testNumber(features$limo.sd.max_min_ratio.scaled, lower = 1) )
  expect_true( testNumber(features$limo.sd.mean, lower = 0) )
  expect_true( testNumber(features$limo.sd.mean.scaled, lower = 0) )
  expect_identical(features$limo.costs_fun_evals, 0L)
  expect_true( testNumber(features$limo.costs_runtime, lower = 0) )
})

test_that("calculateLinearModelFeatures -- second use case", {
  A = rbind(c(0, 0), c(0, 3), c(4, 3))
  feat.object = createFeatureObject(X = A, y = 1:3, blocks = 1)
  features = calculateLinearModelFeatures(feat.object)
  expect_identical(features$limo.length.sd, NA_real_)
  expect_identical(features$limo.cor, NaN)
  expect_identical(features$limo.cor.scaled, NaN)
  expect_identical(features$limo.ratio.sd, NA_real_)
  expect_identical(features$limo.sd.max_min_ratio, NA_real_)
  expect_identical(features$limo.sd.max_min_ratio.scaled, NA_real_)
  expect_identical(features$limo.sd.mean, NA_real_)
  expect_identical(features$limo.sd.mean.scaled, NA_real_)
})
