context("calculateLinModCoefficients")

test_that("A cell mapping-enabled FeatureObject is required", {
  feat.object = createFeatureObject(init = iris[, -5], objective = "Sepal.Length")
  expect_error(calculateLinModCoefficients(feat.object))
})

test_that("calculateLinModCoefficients -- first use case", {
  feat.object = createFeatureObject(init = iris[, -5], objective = "Sepal.Length", blocks = 3)
  features = calculateLinModCoefficients(feat.object)
  expect_equal(length(features), 12)
  expect_is(features, class = "list")
  expect_equal(as.character(sapply(features, class)), rep("numeric", 12))
  expect_true( testNumber(features$lmcoeff.avg.length, lower = 0) )
  expect_true( testNumber(features$lmcoeff.avg.length.scaled, lower = 0, upper = 1) )
  expect_true( testNumber(features$lmcoeff.length.mean, lower = 0) )
  expect_true( testNumber(features$lmcoeff.length.sd, lower = 0) )
  expect_true( testNumber(features$lmcoeff.cor, lower = -1, upper = 1) )
  expect_true( testNumber(features$lmcoeff.cor.scaled, lower = -1, upper = 1) )
  expect_true( testNumber(features$lmcoeff.ratio.mean) )
  expect_true( testNumber(features$lmcoeff.ratio.sd, lower = 0) )
  expect_true( testNumber(features$lmcoeff.sd.max_min_ratio, lower = 1) )
  expect_true( testNumber(features$lmcoeff.sd.max_min_ratio.scaled, lower = 1) )
  expect_true( testNumber(features$lmcoeff.sd.mean, lower = 0) )
  expect_true( testNumber(features$lmcoeff.sd.mean.scaled, lower = 0) )
})

test_that("calculateLinModCoefficients -- second use case", {
  A = rbind(c(0, 0), c(0, 3), c(4, 3))
  feat.object = createFeatureObject(X = A, y = 1:3, blocks = 1)
  features = calculateLinModCoefficients(feat.object)
  expect_identical(features$lmcoeff.length.sd, NA_real_)
  expect_identical(features$lmcoeff.cor, NaN)
  expect_identical(features$lmcoeff.cor.scaled, NaN)
  expect_identical(features$lmcoeff.ratio.sd, NA_real_)
  expect_identical(features$lmcoeff.sd.max_min_ratio, NA_real_)
  expect_identical(features$lmcoeff.sd.max_min_ratio.scaled, NA_real_)
  expect_identical(features$lmcoeff.sd.mean, NA_real_)
  expect_identical(features$lmcoeff.sd.mean.scaled, NA_real_)
})
